//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvansFestivals.Domain.Database
{
    using System;
    
    public enum FestivalState : int
    {
        SoldOut = 0,
        StartSale = 1,
        Created = 2,
        Done = 3,
        InProgress = 4
    }
}
