//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvansFestivals.Domain.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Festival
    {
        public Festival()
        {
            this.Comments = new HashSet<Comment>();
            this.Tickets = new HashSet<Ticket>();
            this.TicketAmounts = new HashSet<TicketAmount>();
        }
    
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [StringLength(5000, MinimumLength = 50, ErrorMessage = "Gebruik minimaal 50 tot met maximaal 5000 karakters")]
        public string Description { get; set; }

        [Required]
        public System.DateTime Start { get; set; }
        
        [Required]
        public System.DateTime End { get; set; }

        [Required]
        public string Logo { get; set; }

        [Required]
        public string Banner { get; set; }
        public FestivalState FestivalState { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<TicketAmount> TicketAmounts { get; set; }
    }
}
